use_frameworks!

target 'dSRelay_Example' do
  pod 'dSRelay', :path => '../'

  target 'dSRelay_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
