use_frameworks!

target 'dSRelay_Example' do
  pod 'dSRelay', :path => '../'
  pod 'SwiftSocket'
  pod 'thenPromise'

  target 'dSRelay_Tests' do
    inherit! :search_paths

    pod 'dSRelay', :path => '../'
    pod 'SwiftSocket'
    pod 'thenPromise'
    pod 'Quick', '~> 1.3.2'
    pod 'Nimble', '~> 7.3.1'
    pod 'InstantMock'
  end
end
